# Generated by Django 5.0.7 on 2024-07-19 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('university', models.CharField(choices=[('UCLA', 'ucla'), ('UCSD', 'ucsd'), ('UCI', 'uci')], max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('major', models.CharField(choices=[('Business', 'business'), ('Computer Science', 'computer science')], max_length=100)),
            ],
        ),
    ]
