# Generated by Django 5.0.7 on 2024-07-26 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='yearly_tuition',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
