# Generated by Django 5.0.7 on 2024-07-26 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_student_financial_assistance_student_years_in_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='financial_assistance',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='student',
            name='yearly_tuition',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='student',
            name='years_in_school',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
